---
title: EKN-812 Lecture 2
subtitle: Welfare Measurement; Restrictions on Preferences
author: Jesse Naidoo
institute: University of Pretoria
fontsize: 10pt
output:
 beamer_presentation:
    template: ../../../../../templates/svm-latex-beamer.tex
    keep_tex: false
    incremental: true
#    toc: true
    slide_level: 2
 ioslides_presentation:
    smaller: true
make149: true
bibliography: ../../../../../library.bib
biblio-style: authordate1
---

<style>
slides > slide.backdrop {
  background: white;
  border-bottom: 0px;
  box-shadow: 0 0 0;
}


slides > slide {
  font-family: 'Open Sans', Helvetica, Arial, sans-serif;
  border-bottom: 3px solid  #F66733;
  box-shadow:  0 3px 0 #522D80;

}

.title-slide hgroup h1 {
  color: #522D80;
}



h2 {

  color: #522D80;
}

slides > slide.dark {
  background: #522D80 !important;
  border-bottom: 0;
  box-shadow: 0 0 0;
}

.segue h2 {
  color: white;
}

slides > slide.title-slide {
  border-bottom: 0;
  box-shadow: 0 0 0;
}

ol, ul {

padding-bottom: 10px;

}

</style>


# Loose Ends

## Envelope Theorem

- a direct proof of Shephard's Lemma: consider
  $$
  e(p, u) = p\cdot x^H(p,u)
  $$
- differentiate with respect to $p_i$:
  $$
  \frac{\partial e}{\partial p_i} = x_i^H + \sum^n_{j=1}p_j\frac{\partial x^H_j}{\partial p_i}
  $$
- but, we can ignore all the indirect effects:
    - use the utility constraint $u \equiv u(x^H(p, u))$
    - then, notice that by the first-order conditions,
    $$
    p_j = \lambda\frac{\partial u}{\partial x_j}
    $$
- the envelope theorem says we could have just computed
  $$
  \frac{\partial \mathcal{L}}{\partial p_i} = \frac{\partial e}{\partial p_i}
  $$

## Comparative Statics

- often we won't be able to solve explicitly for demands
    - but, we can still find the sign of, e.g. price and income effects
    - we do this by implicitly differentiating the system of first-order conditions
- e.g. the first-order conditions give us a system
  \begin{eqnarray}
  u_x(x,y) - \lambda p_x & \equiv & 0 \\
  u_y(x,y) - \lambda p_y & \equiv & 0 \\
  m - p_xx - p_yy \equiv 0
  \end{eqnarray}
- if we differentiate with respect to (say) $y$ we get a linear system for the income effects
    - can solve element-by-element using Cramer's rule
    - can often figure out the sign of the denominator from the second-order conditions


## Elasticity of Substitution

- (Hicks-Allen) partial elasticity of substitution between $i$ and $j$ is 
    \begin{eqnarray*}
    \sigma_{ij}(p,u) & = & \frac{e(p,u)e_{ij}(p,u)}{e_i(p,u)e_j(p,u)} = \left. \frac{\partial \log(x_1/x_2)}{\partial \log(p_1/p_2)}\right\rvert_{u \text{  constant}}
    \end{eqnarray*}	
- With two goods, a measure of the curvature of indifference curves
    - Does not generalize well to higher dimensions though 
    - _Morishima_ elasticities are more appropriate then, although non-symmetric
- A different way of defining substitutability: whether the elasticity of substitution $\sigma_{ij}$ is greater or smaller than 1
    - i.e. do changes in the relative price $p_i/p_j$ lead to more than proportional changes in relative quantities?
    - Can show that $\sigma_{ij}$ is related to Hicksian elasticities via the formula
    \begin{eqnarray*}
    \varepsilon^H_{ij} & = & s_j \sigma_{ij}
    \end{eqnarray*}

# Implications of Rational Choice

## Cardinal vs. Ordinal Utility

- the demands generated by $u(x)$ are the same as those generated by $f(u(x))$, where $f' > 0$
    - marginal rates of substitution are the same
    - but diminishing marginal utility can be overturned if $f'' > 0$
- certain types of restrictions are preserved by increasing transformations
    - we call those "ordinal" restrictions (depend only on ranking of bundles)
    - e.g. quasiconcavity, elasticity of substitution, price elasticities
    - concavity is _not_ preserved by monotone transformations
- this sensitivity to how preferences are represented means we are usually skeptical of conclusions that depend on interpersonal comparisons of utility
    - Pareto efficiency does not have this weakness
    - nevertheless, there are important areas (e.g. optimal taxation) which make use of cardinal utility

## Homothetic Preferences

- first, suppose $u(x)$ is homogenous of degree 1
    - e.g. Cobb-Douglas preferences $u(x_1, x_2) = x_1^\alpha x_2^{1-\alpha}$
- then all income elasticities are 1:
    - consider $x^M(p, ty)$ for some $t > 0$
    - what is the indirect utility when you scale up income by $t$?
        - cannot do worse than $tv(p,y) = tu(x^M(p,y))$
        - if strictly better, $x^M(p,y)$ wasn't optimal to begin with
    - thus, $x^M(p, ty) \equiv tx^M(p,y)$ for all $t > 0$
- to complete the proof: differentiate wrt $t$ and evaluate at $t = 1$.
- now, because utility is ordinal, only need that there is some increasing function $f$ such that $f(u(x))$ is homogenous of degree 1

## Integrability

- you may be wondering if rational choice has any _other_ implications besides the NSD Slutsky matrix
    - the answer is **no**
- the formal result is that if you have a demand function $x^M(p, y)$ with a NSD Slutsky matrix, you can always construct a utility function $u(x)$ that "rationalizes the data"
    - in the sense that maximization of $u(x)$ subject to a budget constraint would give you $x^M$ back again
    - this result is only "local"
    - for the details, see @Deaton1980a, Ch. 2.6
- the implication is that if you want sharper predictions, have to make stronger assumptions    
    - many substitution patterns are possible even with a NSD matrix
    - even this is assuming we have exogenous variation in all prices, which we usually don't

# Welfare Measurement

## CV, EV, and Consumer's Surplus

- so far we have been talking about the positive implications of utility theory
- however, consumer theory also has normative uses:
    - tracking changes in the cost of living over time
    - measuring the gains from innovation (new goods)
    - evaluating the distribution of losses (or gains) from government policies
    - inferring the value of non-priced goods (e.g. environmental quality, crime)

## CV, EV and Consumer's Surplus

- consider a change in prices from $p$ to $p'$
- the _equivalent variation_ is the change in income that is _equivalent_ to the price change, starting at the original prices
    - $EV$ implicitly defined by $v(p, y + EV) = v(p', y)$
    - can show this is equivalent to $EV = e(p, u') - y$ where $u' = v(p', y)$
    - the price a consumer is willing to pay to avoid a price increase
- the _compensating variation_ is similar but evaluated at the new prices
    - implicitly defined by $v(p', y - CV) = v(p, y)$
    - equivalently, $CV = y - e(p', u)$ where $u = v(p,y)$ is old level of utility
    - the transfer that _compensates_ for a price change

## CV, EV and Consumer's Surplus

- recall the Hicksian demands are the derivatives of the expenditure function
    - this means we can interpret $EV$ and $CV$ as areas under a Hicksian demand curve
    - but, which ones?
- _consumer surplus_ is the area under a Marshallian demand curve
    - in the case of a normal good,
      $$
      EV \leq \Delta CS \leq CV
      $$
    - for an inferior good the reverse inequalities hold

## Price Indices

- ideal price index for one consumer:
  $$
  \pi_{t+1, t} = \frac{e(p(t+1), u) - e(p(t), u)}{e(p(t), u)}
  $$
- problems:
    - RHS depends on $u$, unless preferences are homothetic
    - we don't know preferences (and hence $e(p,u)$)
- obviously, heterogeneity in preferences makes this more complicated
- two common types of price indices:
    - _Laspeyres_ indices use initial bundle as weights for later prices
    - _Paasche_ indices use current quantities as weights for earlier prices
    - _chained_ indices: break up long periods into accumulation of short-term changes
- an important practical issue is how often to update the weights
    - trade off accuracy vs cost of data collection
- dealing with new goods (and exit of old goods) is another important issue
    - one strategy: compare new goods to "appropriate" average of existing ones
    - important to use chained indices here because demand patterns shift over time

# Composite Commodity Theorem

## Composite Commodity Theorem

- suppose we have three goods, $x_1, x_2$ and $x_3$
    - initial prices are $p^0$
    - however, $(p_2, p_3)$ always move "in parallel"
    - we will see that we can define an artificial "composite commodity" and proceed as if there are only two goods
- let $e^*(p_1, \theta, u) = e(p_1, \theta p_2^0, \theta p_3^0, u)$ 
    - here $e(p,u)$ is the usual expenditure function
    - we are suppressing $(p_2, p_3)$ as an argument of $e^*$
- notice that $e^*$ has all the usual properties of a cost function
    - increasing in $(p, \theta)$ and in $u$
    - homogeneous of degree 1 in $(p, \theta)$
    - concave in $(p, \theta)$

## Composite Commodity Theorem

- this means we can define the artificial "good" $z = p_2^0x_2 + p_3^0x_3$ with price $\theta$ and treat demands as arising from a two-good system in $(x_1, z)$
    - this is useful because we want to focus on $x_1$
    - not on the detailed composition of $z$
- heavily used in macroeconomics 
    - aggregate all consumption in a period into $c_t$
- more generally: if you want to aggregate to broad groups, weight by relative prices    

## Alchian and Allen Effect

- suppose we have two "similar" goods which are substitutes
    - high and low quality wine, apples, etc
    - should be in comparable (physical) units
- now add a constant $t$ to each price (e.g. transportation costs)
- consider $e^*(t, p_3, u) = e(p_1 + t, p_2 + t, p_3, u)$
    - note we are suppressing $(p_1, p_2)$ as an argument to $e^*$, but it's there
    - define the artificial commodity $z = x_1 + x_2$ as above
- Alchian and Allen effect: relative consumption of high-quality good is higher with high $t$
    - best South African wines are exported (similar for France, Australia, California)
    - "shipping the good apples out"
- can show that
    \begin{eqnarray*}
    \frac{\partial}{\partial t}\left(\frac{x_1}{x_2}\right) > 0 & \text{ if } & \varepsilon^H_{23} - \varepsilon^H_{13} \geq 0 
    \end{eqnarray*}
    - possible counterexamples?

# Quasilinear Approximations

## Quasilinear Approximation

- for some $\varepsilon > 0$ and $a > 0$,
    \begin{eqnarray*}
    u(c, q) & = & \left\{\begin{array}{ll} c + \left(\frac{a}{1-\varepsilon^{-1}}\right)q^{1-\varepsilon^{-1}} & \text{ if $\varepsilon \neq 1$ } \\ & \\ c + a\log(q) & \text{ if $\varepsilon = 1$} \end{array}\right.
    \end{eqnarray*}
- Can show that if $y$ is large enough Marshallian elasticity is exactly $\varepsilon$. (If $y$ is too small, spend entire budget on $q$, so $c^M(p,y) = 0$.)
    - What are the income elasticities of $c$ and $q$? 
    - What is the elasticity of substitution between $c$ and $q$?
- These preferences are very useful for studying the demand for one good in isolation; $c$ is a "composite commodity" consisting of "all other goods"
- Can think of quasilinear preferences as a limiting case where there are
    - many other goods
    - none of them occupies a large budget share
    - and the elasticity of substitution between any pair of goods is bounded
    - See @Vives1987 for precise sufficient conditions

# Separable Preferences

## Weak Separability

- suppose you can group goods e.g.
  \begin{eqnarray*}
  u & = & u(v,w) \\
  v & = & f(x_1, x_2) \\
  w & = & g(y_1, y_2)
  \end{eqnarray*}
- we say $(x_1, x_2)$ is _weakly separable_ from $(y_1, y_2)$
    - immediate implication: can mechanically solve consumer's problem in two stages
    \begin{eqnarray*}
    \pi_v^*(p_{x,1}, p_{x,2}, v) & = & \min p_{x,1}x_1 + p_{x,2}x_2 \text{ s.t. } f(x_1, x_2) \geq v \\
    \pi_w^*(p_{y,1}, p_{y,2}, v) & = & \min p_{y,1}y_1 + p_{y,2}y_2 \text{ s.t. } g(y_1, y_2) \geq w
    \end{eqnarray*}
    - then, solve "upper-level" consumer's problem
    $$
    \min \pi_v(v) + \pi_w(w) \text{ s.t. } u(v,w) \geq u
    $$
- why is it especially useful if $f$ and $g$ are homothetic?

## Weak Separability

- more subtly, MRS between $x$-goods does not depend on $y$-goods
    - this restricts substitution patterns and cross-price effects
- in particular, the cross-price elasticities for goods in different groups
    - have to be proportional to the income effects within each group
    - intuition: marginal rates of substitution only depend on own-group prices
    - see @Deaton1980a, Ch. 5.2

## Strong (Additive) Separability

- suppose preferences can be represented as
  $$
  u(x) = \sum^n_{i=1} v_i(x_i)
  $$
- examples:
    - $u(x_1, x_2) = 1 + x_1 + x_2 + x_1x_2$ is additively separable
    - $u(x_1, x_2) = x_1 + x_2 + x_1x_2^2$ is **not** - why?
- if all the $v_i$ are increasing and concave:
    - all goods are normal
    - no (net) complements
- used a lot for
    - intertemporal choice
    - problems with uncertainty (expected-utility preferences)
- some problems where additivity is "too restrictive"
    - habits, addiction
    - social interactions

## Strong (Additive) Separability

- obviously this is restrictive
    - the other side to restrictiveness is that you need less data
    - e.g. @Deaton1980a shows that the Marshallian price elasticities satisfy
      \begin{eqnarray*}
      \varepsilon^M_{ii} & = & \phi\eta_i -\eta_i s_i (1 + \phi\eta_i) \\
      \varepsilon^M_{ij} & = & -\eta_i s_j (1 + \phi\eta_j)
      \end{eqnarray*}
    - here $\phi$ is some constant that depends on preferences and prices
- important point is that you only need
  - the budget shares (just accounting data)
  - the income elasticities ("easy" to estimate)
  - one price elasticity
  - and then you can identify all cross-price elasticities
 
## References
